[package]
name = "rastair2-types"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
rust-htslib.workspace = true
serde.workspace = true
smol_str.workspace = true
thiserror = "2.0.12"
winnow = "0.7.11"

[dev-dependencies]
insta.workspace = true
proptest.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage, coverage_nightly)',
] }
