image: rust:1.92 # keep in sync with `rust-toolchain.yml`

options:
  max-time: 30

definitions:
  caches:
    cargo-index: /usr/local/cargo/registry/index
    cargo-cache: /usr/local/cargo/registry/cache
    cargo-git: /usr/local/cargo/git/
    cargo-local-bin: .bin/

pipelines:
  default:
    - parallel:
        steps:
          - step:
              name: Formatting
              fail-fast: false
              script:
                - rustup component add rustfmt
                - cargo fmt -- --check
          - step:
              name: Test
              caches:
                - cargo-index
                - cargo-cache
                - cargo-git
                - cargo-local-bin
              script:
                - apt-get update && apt-get install -y --no-install-recommends curl unzip libclang-dev cmake samtools tabix
                - cargo xtask test

  tags:
    "v*":
      - parallel:
          steps:
            - step:
                name: Compile & upload docs
                image: rust:1.92
                caches:
                  - cargo-index
                  - cargo-cache
                  - cargo-git
                  - cargo-local-bin
                script:
                  - apt-get update
                  - apt-get install -y --no-install-recommends curl unzip cmake libclang-dev
                  # Install AWS CLI v2 (simple & consistent for OIDC)
                  - curl -sSLo awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
                  - unzip -q awscliv2.zip
                  - ./aws/install -b /usr/local/bin

                  - cargo install mdbook@0.4.52 mdbook-mermaid@0.16.2 mdbook-katex@0.9.4 mdbook-admonish@1.20.0
                  - cargo xtask docs
                  - export AWS_DEFAULT_REGION="${AWS_REGION_DOC}"
                  - export AWS_REGION="${AWS_REGION_DOC}"
                  - export S3_BUCKET=${S3_BUCKET_DOC}
                  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_DOC}
                  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY_DOC}
                  - ls
                  - aws s3 sync ./docs/book s3://${S3_BUCKET}/
                  - aws cloudfront create-invalidation --distribution-id E12QS42FTTJKFT --paths "/*"


