[package]
name = "rastair2"
description = "Fast and flexible extraction of methylation information from BAM files"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
license = "AGPL-3.0-only"
authors = ["Benjamin Schuster-Boeckler", "Pascal Hertleif <pascal@softleif.se>"]
readme = "README.md"

[package.metadata.bin]
cargo-binstall = { version = "1.14.1" }
cargo-llvm-cov = { version = "0.6.17" }
cargo-insta = { version = "1.43.1" }
cargo-nextest = { version = "0.9.100" }

mdbook = { version = "0.4.51" }
mdbook-katex = { version = "0.9.4" }

[workspace]
members = ["crates/*", "tools/*"]

[workspace.dependencies]
color-eyre = "0.6.5"
smallvec = { version = "2.0.0-alpha.11", features = ["serde", "std"] }
smol_str = { version = "0.3.2", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
cstr8 = "0.1.4"
rust-htslib = { version = "0.49.0", git = "https://github.com/killercup/rust-htslib.git", branch = "feature/cstr8", default-features = false, features = [
  "bzip2",
  "lzma",
  "libdeflate",
] }
tracing = { version = "0.1.41", features = ["release_max_level_debug"] }

insta = { version = "1.43.1", features = ["filters"] }
insta-cmd = "0.6.0"
pastey = "0.1.0"
proptest = "1.7.0"
tempfile = "3.20.0"

[dependencies]
rust-htslib = { workspace = true }
color-eyre = { workspace = true }
smallvec = { workspace = true }
smol_str = { workspace = true }
serde = { workspace = true }
cstr8 = { workspace = true }
tracing = { workspace = true }

# bio tools
bgzip = { version = "0.3.1", features = ["zlib-ng"] }
bio = "2.2.0"
rastair2-vcf = { version = "0.1.0", path = "crates/rastair2-vcf" }

# cli stuff
clap = { version = "4.5.35", features = ["derive", "env"] }
clap_complete_command = "0.6.1"
clio = { version = "0.3.5", features = ["clap", "clap-parse", "pipe"] }

# multithreading
rayon = "1.10.0"
ordered-channel = { version = "1.2.0", features = ["crossbeam-channel"] }
mimalloc = { version = "0.1.47", features = ["override"] }

# I/O
lz4 = "1.28.1"
rmp-serde = "1.3.0"

# utils
probability = "0.20.3"
rustc-hash = "2.1.1"
pastey = "0.1.0"
winnow = { version = "0.7.6", features = ["simd"] }

# error handling and logging
thiserror = "2.0.12"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
readable = { version = "0.16.0", default-features = false, features = [
  "byte",
  "num",
] }
clap-markdown = "0.1.5"
clap-num = "1.2.0"
libc = "0.2.174"
rastair2-types = { version = "0.1.0", path = "crates/rastair2-types" }
serde_json = "1.0.140"

[dev-dependencies]
insta = { workspace = true }
insta-cmd = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage, coverage_nightly)',
] }

[lints.clippy]
dbg_macro = { level = "warn" }
unwrap_used = { level = "deny" }
panic = { level = "deny" }
# indexing_slicing = { level = "deny" }
undocumented_unsafe_blocks = { level = "deny" }
unwrap_in_result = { level = "deny" }
ok_expect = { level = "deny" }

# Only output useful program output to stdout not forgotten debug code :)
print_stdout = { level = "warn" }

# Pascal is bad with numbers
cast_lossless = { level = "warn" }
cast_possible_truncation = { level = "warn" }
cast_possible_wrap = { level = "warn" }
comparison_chain = { level = "warn" }
range_minus_one = { level = "warn" }
range_plus_one = { level = "warn" }

# Some pedantic lints we like
doc_link_with_quotes = { level = "warn" }
doc_markdown = { level = "warn" }
explicit_into_iter_loop = { level = "warn" }
format_collect = { level = "warn" }
format_push_string = { level = "warn" }
index_refutable_slice = { level = "warn" }
default_trait_access = { level = "warn" }
rc_buffer = { level = "warn" }
return_and_then = { level = "warn" }
same_name_method = { level = "warn" }
string_to_string = { level = "warn" }
inefficient_to_string = { level = "warn" }
manual_let_else = { level = "warn" }
manual_is_variant_and = { level = "warn" }
manual_assert = { level = "warn" }
manual_string_new = { level = "warn" }
option_option = { level = "warn" }
equatable_if_let = { level = "warn" }

[profile.dev.package]
rand_chacha.opt-level = 3
proptest.opt-level = 3
insta.opt-level = 3
similar.opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
