[package]
name = "rastair"
description = "Fast and flexible extraction of methylation information from BAM files"
version = "2.1.1"
edition = "2024"
rust-version = "1.92.0"
license-file = "LICENSE.txt"
authors = ["Benjamin Schuster-Boeckler", "Pascal Hertleif <pascal@softleif.se>"]
readme = "README.md"

[package.metadata.bin]
cargo-binstall = { version = "1.17.3" }
cargo-llvm-cov = { version = "0.8.4" }
cargo-insta = { version = "1.46.1" }
cargo-nextest = { version = "0.9.114" }
cargo-pgo = { version = "0.3.0" }

mdbook = { version = "0.4.52" }
mdbook-katex = { version = "0.9.4" }
mdbook-mermaid = { version = "0.16" }
mdbook-admonish = { version = "1.20.0" }
mdbook-yapp = { version = "1.2.4" }

[workspace]
members = ["crates/*", "tools/*"]

[workspace.dependencies]
color-eyre = "0.6.5"
serde = { version = "1.0.219", features = ["derive", "rc"] }
cstr8 = "0.1.4"
rust-htslib = { version = "1.0.0", git = "https://github.com/Softleif/rust-htslib.git", default-features = false, features = [
    "libdeflate",
    "bzip2",
    "lzma",
    "static",
] }
tracing = { version = "0.1.41", features = ["release_max_level_debug"] }

insta = { version = "1.46.1", features = ["filters"] }
insta-cmd = "0.6.0"
pastey = "0.2.0"
proptest = "1.7.0"
tempfile = "3.24.0"

[dependencies]
color-eyre = { workspace = true }
serde = { workspace = true, features = ["derive"] }
cstr8 = { workspace = true }
tracing = { workspace = true }

rastair-vcf = { version = "0.2.0", path = "crates/rastair-vcf" }
rastair-types = { version = "0.2.0", path = "crates/rastair-types" }

# bio tools
bio-types = "1"
noodles = { version = "0.108.0", features = ["tabix", "csi", "bgzf", "core"] }
noodles-bgzf = { version = "0.46.0", features = ["libdeflate"] }
rust-htslib = { workspace = true }

# ml
biosphere = { git = "https://github.com/Softleif/biosphere", version = "0.5.0", features = [
    "serde",
    "gpu",
] }
ndarray = "0.17.2"
rand = "0.9.2"

# cli stuff
clap = { version = "4.5.35", features = ["derive", "env"] }
clap_complete_command = "0.6.1"
clio = { version = "0.3.5", features = ["clap", "clap-parse", "pipe"] }

# multithreading
rayon = "1.10.0"
ordered-channel = { version = "1.2.0", features = ["crossbeam-channel"] }
mimalloc = { version = "0.1.48", features = ["override", "v3"] }

# I/O
lz4 = "1.28.1"
rmp-serde = "1.3.0"
serde_json = { version = "1.0.140", features = ["preserve_order"] }

# utils
probability = "0.20.3"
rustc-hash = "2.1.1"
pastey = { workspace = true }
winnow = { version = "1.0.0", features = ["simd"] }

# error handling and logging
thiserror = "2.0.12"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
readable = { version = "0.16.0", default-features = false, features = [
    "byte",
    "num",
] }
clap-markdown = { version = "0.1.5", git = "https://github.com/Softleif/clap-markdown", rev = "88f5801fb107ac97730b8e47acd8a0cee516e85a" }
clap-num = "1.2.0"
libc = "0.2.174"
better_default = "1.0.5"
tabled = "0.20"

# just so that rust-htslib builds it statically
bzip2-sys = { version = "0.1.13", features = ["static"] }
pollster = "0.4.0"
jiff = "0.2.23"
bgzf = "0.3.0"

[dev-dependencies]
insta = { workspace = true }
insta-cmd = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
pastey = { workspace = true }

[features]
external-tool-tests = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage, coverage_nightly)',
] }

[lints.clippy]
dbg_macro = "warn"
panic = "deny"
indexing_slicing = "warn"
undocumented_unsafe_blocks = "deny"
unwrap_used = "warn"
unwrap_in_result = "warn"
ok_expect = "warn"

# Only output useful program output to stdout not forgotten debug code :)
print_stdout = "warn"

# Pascal is bad with numbers
cast_lossless = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
comparison_chain = "warn"
range_minus_one = "warn"
range_plus_one = "warn"
lossy_float_literal = "warn"
non_zero_suggestions = "warn"

# Some pedantic lints we like
doc_link_with_quotes = "warn"
doc_markdown = "warn"
explicit_into_iter_loop = "warn"
format_collect = "warn"
format_push_string = "warn"
index_refutable_slice = "warn"
default_trait_access = "warn"
rc_buffer = "warn"
mem_forget = "warn"
return_and_then = "warn"
same_name_method = "warn"
string_to_string = "warn"
inefficient_to_string = "warn"
manual_let_else = "warn"
manual_is_variant_and = "warn"
manual_assert = "warn"
manual_string_new = "warn"
option_option = "warn"
equatable_if_let = "warn"
allow_attributes_without_reason = "warn"
infinite_loop = "warn"
create_dir = "warn"
pathbuf_init_then_push = "warn"

[profile.dev.package]
rand_chacha.opt-level = 3
proptest.opt-level = 3
insta.opt-level = 3
similar.opt-level = 3
biosphere.opt-level = 3
ndarray.opt-level = 3
lz4.opt-level = 3
rust-htslib.opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
