[package]
name = "rastair-types"
version = "0.2.0"
edition = "2024"
license-file = "../LICENSE.txt"

[dependencies]
color-eyre.workspace = true
rust-htslib.workspace = true
serde.workspace = true
thiserror = "2.0.12"
winnow = "1.0.0"
smallvec = { version = "2.0.0-alpha.12", features = ["serde", "std"] }
smol_str = { version = "0.3.4", features = ["serde"] }

[dev-dependencies]
insta.workspace = true
proptest.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage, coverage_nightly)',
] }
