[alias]
xtask = "run --package xtask --"
bin = ["run", "--package", "cargo-bin", "--"]
binstall = ["bin", "cargo-binstall"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
pgo = ["bin", "cargo-pgo"]
