[package]
name = "smallarcvec"
description = "An Arc<u8> with an inline optimization for small vectors"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Pascal Hertleif <pascal@softleif.se>"]

[dev-dependencies]
proptest = "1.6.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
