[package]
name = "rastair-vcf"
version = "0.1.0"
description = "A VCF writer for Rastair."
authors = ["Pascal Hertleif <pascal@softleif.se>"]
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
rust-htslib = { workspace = true }
color-eyre = { workspace = true }
serde = { workspace = true }
cstr8 = { workspace = true }
rastair-types = { version = "0.1.0", path = "../rastair-types" }

[dev-dependencies]
insta = { workspace = true }
insta-cmd = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
pastey = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(coverage, coverage_nightly)',
] }

[lints.clippy]
unwrap_used = { level = "deny" }
panic = { level = "deny" }
indexing_slicing = { level = "deny" }
undocumented_unsafe_blocks = { level = "deny" }
unwrap_in_result = { level = "deny" }
ok_expect = { level = "deny" }
