[book]
authors = ["Benjamin Schuster-Boeckler","Pascal Hertleif"]
language = "en"
src = "src"
title = "Rastair"

[preprocessor.glossary]
command = "cargo run -p mdbook-glossary"
glossary = "src/glossary.yaml"

[preprocessor.katex]
after = ["links"]
