---
title: "Comparison of rastair 1 to rastair 2"
author: "Benjamin Schuster-Boeckler"
date: "`r Sys.Date()`"
output: html_document
params:
  test_bam: "/Users/schuster/Documents/Programming/Rust/rastair2/tests/data/test.bam"
  test_fasta: "/Users/schuster/Documents/Programming/Rust/rastair2/tests/data/test.fasta.gz"
  rastair_bin: "/Users/schuster/Documents/Programming/Rust/rastair/target/release/rastair"
  rastair2_bin: "/Users/schuster/Documents/Programming/Rust/rastair2/target/release/rastair2"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load_packages}
suppressPackageStartupMessages({
  library("data.table")
  library("ggplot2")
})
```

## Comparison of beta values between rastair 1 and rastair 2
```{r run_rastair}
rastair.1 <- fread(cmd=paste0(params$rastair_bin, " call -q 0 -Q 1 -l chr19 -r ", params$test_fasta, " ", params$test_bam), header=TRUE, stringsAsFactors=TRUE)
setnames(rastair.1, 1, "chr")

rastair.2 <- fread(cmd=paste0(params$rastair2_bin, " call --calling=thresholds -l chr19 -r ", params$test_fasta, " ", params$test_bam, '| bcftools query -i "CPG==1" -f "%CHROM\\t%POS0\\t%POS\\t%REF\\t%ALT\\t%AS_SB[\\t%M5mC\\t%GT\\t%DP]\n"'), header=FALSE, stringsAsFactors=FALSE, na.strings=c("."))
setnames(rastair.2, c("chr", "start", "end", "ref", "alt", "strand_bias", "beta", "genotype", "depth"))
rastair.2[, chr:=as.factor(chr)]
```

Plot r1 vs r2:

```{r}
setkey(rastair.1, chr, start, end)
setkey(rastair.2, chr, start, end)
r1_vs_r2 <- rastair.1[rastair.2, nomatch=NULL][, .(chr, start, end, r1 = mod/(mod+unmod), r2=beta)]
r1_vs_r2.long <- melt(r1_vs_r2, id.vars=c("chr", "start", "end"), value.name = "beta", variable.name="method")

ggplot(r1_vs_r2, aes(x=r1, y=r2)) + geom_point()
```

